### ISSUE TITLE
Convert PHP object to plain array

### ISSUE THREAD

**Issue by e1himself** [mindplay-dk/jsonfreeze#2]
Hi!

Is it possible to use this library to convert PHP objects to plain PHP array? (that array can be passed to json_encode and return same result as `JsonSerialziler::serialize()` returns).

It would be cool to have this feature to use the library for saving objects to Mongo.
As now you need to do (fake code):

```php
$mongo->save(json_decode($jsonSerializer->serialize($employee))));
```

But there are obviously unneccessary *array->json->array* conversions. 

I see it something like that:

```php
$id = $mongo->save($jsonSerializer->toArray($employee));
// and then
$jsonSerializer->fromArray($mongo->get($id));
```

**Comment by mindplay-dk** [comment]
Well, there is no way around the string creation, as a bunch of (internal) methods construct strings directly, as this was the objective of the library.

> there are obviously unneccessary array->json->array conversions

Short of doing some major refactoring work (and compromising some of the source-control friendliness, which is an objective) there's no way around this.

You could probably use the code as a basis for creating a library to do that, but it's outside the scope of this library.

**Comment by e1himself** [comment]
Ok. Thanks for explanation.
