### ISSUE TITLE
Not working with array

### ISSUE THREAD

**Issue by avz-cmf** [mindplay-dk/jsonfreeze#5]
use mindplay\jsonfreeze\JsonSerializer;
$array = [   'a',    'b' => 'b '];
$serializer = new JsonSerializer();
$serializedValue = $serializer->serialize($array);
$value = $serializer->unserialize($serializedValue);
var_dump($value); //null

**Comment by mindplay-dk** [comment]
Thanks for the bug-report - you can install `^0.3.2` now, which fixes this issue.
